! -----------------------------------------------------------------------------
! File: gruvbox-dark.xresources
! Description: Retro groove colorscheme generalized
! Author: morhetz <morhetz@gmail.com>
! Source: https://github.com/morhetz/gruvbox-generalized
! Last Modified: 6 Sep 2014
! -----------------------------------------------------------------------------

! hard contrast: background: #1d2021
background: #0a0e0a
! background: #282828
! soft contrast: background: #32302f
foreground: #62ff94
! Black + DarkGrey
color0:  #1e2a1b
color8:  #8ca391
! DarkRed + Red
color1:  #ff4b4b
color9:  #ff7171
! DarkGreen + Green
color2:  #1cc24b
color10: #2eff6a
! DarkYellow + Yellow
color3:  #ffa83d
color11: #e6ff57
! DarkBlue + Blue
color4:  #30b3ff
color12: #00efff
! DarkMagenta + Magenta
color5:  #c770ff
color13: #24f6d9
! DarkCyan + Cyan
color6:  #24f6d9
color14: #00efff
! LightGrey + White
color7:  #8ca391
color15: #62ff94

#Cursor 
cursor: #62ff94
